// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockIPeerService is an autogenerated mock type for the IPeerService type
type MockIPeerService struct {
	mock.Mock
}

type MockIPeerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPeerService) EXPECT() *MockIPeerService_Expecter {
	return &MockIPeerService_Expecter{mock: &_m.Mock}
}

// AddPeer provides a mock function with given fields: peer
func (_m *MockIPeerService) AddPeer(peer string) {
	_m.Called(peer)
}

// MockIPeerService_AddPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPeer'
type MockIPeerService_AddPeer_Call struct {
	*mock.Call
}

// AddPeer is a helper method to define mock.On call
//   - peer string
func (_e *MockIPeerService_Expecter) AddPeer(peer interface{}) *MockIPeerService_AddPeer_Call {
	return &MockIPeerService_AddPeer_Call{Call: _e.mock.On("AddPeer", peer)}
}

func (_c *MockIPeerService_AddPeer_Call) Run(run func(peer string)) *MockIPeerService_AddPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIPeerService_AddPeer_Call) Return() *MockIPeerService_AddPeer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPeerService_AddPeer_Call) RunAndReturn(run func(string)) *MockIPeerService_AddPeer_Call {
	_c.Run(run)
	return _c
}

// GetCounterValue provides a mock function with no fields
func (_m *MockIPeerService) GetCounterValue() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCounterValue")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockIPeerService_GetCounterValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCounterValue'
type MockIPeerService_GetCounterValue_Call struct {
	*mock.Call
}

// GetCounterValue is a helper method to define mock.On call
func (_e *MockIPeerService_Expecter) GetCounterValue() *MockIPeerService_GetCounterValue_Call {
	return &MockIPeerService_GetCounterValue_Call{Call: _e.mock.On("GetCounterValue")}
}

func (_c *MockIPeerService_GetCounterValue_Call) Run(run func()) *MockIPeerService_GetCounterValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPeerService_GetCounterValue_Call) Return(_a0 int64) *MockIPeerService_GetCounterValue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPeerService_GetCounterValue_Call) RunAndReturn(run func() int64) *MockIPeerService_GetCounterValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetPeersList provides a mock function with no fields
func (_m *MockIPeerService) GetPeersList() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPeersList")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockIPeerService_GetPeersList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPeersList'
type MockIPeerService_GetPeersList_Call struct {
	*mock.Call
}

// GetPeersList is a helper method to define mock.On call
func (_e *MockIPeerService_Expecter) GetPeersList() *MockIPeerService_GetPeersList_Call {
	return &MockIPeerService_GetPeersList_Call{Call: _e.mock.On("GetPeersList")}
}

func (_c *MockIPeerService_GetPeersList_Call) Run(run func()) *MockIPeerService_GetPeersList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPeerService_GetPeersList_Call) Return(_a0 []string) *MockIPeerService_GetPeersList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPeerService_GetPeersList_Call) RunAndReturn(run func() []string) *MockIPeerService_GetPeersList_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function with given fields: eventID
func (_m *MockIPeerService) Increment(eventID string) error {
	ret := _m.Called(eventID)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIPeerService_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type MockIPeerService_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - eventID string
func (_e *MockIPeerService_Expecter) Increment(eventID interface{}) *MockIPeerService_Increment_Call {
	return &MockIPeerService_Increment_Call{Call: _e.mock.On("Increment", eventID)}
}

func (_c *MockIPeerService_Increment_Call) Run(run func(eventID string)) *MockIPeerService_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIPeerService_Increment_Call) Return(_a0 error) *MockIPeerService_Increment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPeerService_Increment_Call) RunAndReturn(run func(string) error) *MockIPeerService_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// JoinPeer provides a mock function with given fields: peer
func (_m *MockIPeerService) JoinPeer(peer string) {
	_m.Called(peer)
}

// MockIPeerService_JoinPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinPeer'
type MockIPeerService_JoinPeer_Call struct {
	*mock.Call
}

// JoinPeer is a helper method to define mock.On call
//   - peer string
func (_e *MockIPeerService_Expecter) JoinPeer(peer interface{}) *MockIPeerService_JoinPeer_Call {
	return &MockIPeerService_JoinPeer_Call{Call: _e.mock.On("JoinPeer", peer)}
}

func (_c *MockIPeerService_JoinPeer_Call) Run(run func(peer string)) *MockIPeerService_JoinPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIPeerService_JoinPeer_Call) Return() *MockIPeerService_JoinPeer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPeerService_JoinPeer_Call) RunAndReturn(run func(string)) *MockIPeerService_JoinPeer_Call {
	_c.Run(run)
	return _c
}

// NewMockIPeerService creates a new instance of MockIPeerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPeerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPeerService {
	mock := &MockIPeerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
