// Code generated by mockery v2.53.5. DO NOT EDIT.

package client

import mock "github.com/stretchr/testify/mock"

// MockIClient is an autogenerated mock type for the IClient type
type MockIClient struct {
	mock.Mock
}

type MockIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIClient) EXPECT() *MockIClient_Expecter {
	return &MockIClient_Expecter{mock: &_m.Mock}
}

// Heartbeat provides a mock function with given fields: peer, selfID
func (_m *MockIClient) Heartbeat(peer string, selfID string) error {
	ret := _m.Called(peer, selfID)

	if len(ret) == 0 {
		panic("no return value specified for Heartbeat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(peer, selfID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIClient_Heartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Heartbeat'
type MockIClient_Heartbeat_Call struct {
	*mock.Call
}

// Heartbeat is a helper method to define mock.On call
//   - peer string
//   - selfID string
func (_e *MockIClient_Expecter) Heartbeat(peer interface{}, selfID interface{}) *MockIClient_Heartbeat_Call {
	return &MockIClient_Heartbeat_Call{Call: _e.mock.On("Heartbeat", peer, selfID)}
}

func (_c *MockIClient_Heartbeat_Call) Run(run func(peer string, selfID string)) *MockIClient_Heartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIClient_Heartbeat_Call) Return(_a0 error) *MockIClient_Heartbeat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIClient_Heartbeat_Call) RunAndReturn(run func(string, string) error) *MockIClient_Heartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// JoinCluster provides a mock function with given fields: peerId, selfId
func (_m *MockIClient) JoinCluster(peerId string, selfId string) ([]string, error) {
	ret := _m.Called(peerId, selfId)

	if len(ret) == 0 {
		panic("no return value specified for JoinCluster")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]string, error)); ok {
		return rf(peerId, selfId)
	}
	if rf, ok := ret.Get(0).(func(string, string) []string); ok {
		r0 = rf(peerId, selfId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(peerId, selfId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIClient_JoinCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinCluster'
type MockIClient_JoinCluster_Call struct {
	*mock.Call
}

// JoinCluster is a helper method to define mock.On call
//   - peerId string
//   - selfId string
func (_e *MockIClient_Expecter) JoinCluster(peerId interface{}, selfId interface{}) *MockIClient_JoinCluster_Call {
	return &MockIClient_JoinCluster_Call{Call: _e.mock.On("JoinCluster", peerId, selfId)}
}

func (_c *MockIClient_JoinCluster_Call) Run(run func(peerId string, selfId string)) *MockIClient_JoinCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIClient_JoinCluster_Call) Return(_a0 []string, _a1 error) *MockIClient_JoinCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIClient_JoinCluster_Call) RunAndReturn(run func(string, string) ([]string, error)) *MockIClient_JoinCluster_Call {
	_c.Call.Return(run)
	return _c
}

// SendIncrement provides a mock function with given fields: peer, selfId, eventId
func (_m *MockIClient) SendIncrement(peer string, selfId string, eventId string) error {
	ret := _m.Called(peer, selfId, eventId)

	if len(ret) == 0 {
		panic("no return value specified for SendIncrement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(peer, selfId, eventId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIClient_SendIncrement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendIncrement'
type MockIClient_SendIncrement_Call struct {
	*mock.Call
}

// SendIncrement is a helper method to define mock.On call
//   - peer string
//   - selfId string
//   - eventId string
func (_e *MockIClient_Expecter) SendIncrement(peer interface{}, selfId interface{}, eventId interface{}) *MockIClient_SendIncrement_Call {
	return &MockIClient_SendIncrement_Call{Call: _e.mock.On("SendIncrement", peer, selfId, eventId)}
}

func (_c *MockIClient_SendIncrement_Call) Run(run func(peer string, selfId string, eventId string)) *MockIClient_SendIncrement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIClient_SendIncrement_Call) Return(_a0 error) *MockIClient_SendIncrement_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIClient_SendIncrement_Call) RunAndReturn(run func(string, string, string) error) *MockIClient_SendIncrement_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIClient creates a new instance of MockIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIClient {
	mock := &MockIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
