// Code generated by mockery v2.53.5. DO NOT EDIT.

package peerStore

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockIPeerStore is an autogenerated mock type for the IPeerStore type
type MockIPeerStore struct {
	mock.Mock
}

type MockIPeerStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPeerStore) EXPECT() *MockIPeerStore_Expecter {
	return &MockIPeerStore_Expecter{mock: &_m.Mock}
}

// AddPeer provides a mock function with given fields: peerId
func (_m *MockIPeerStore) AddPeer(peerId string) {
	_m.Called(peerId)
}

// MockIPeerStore_AddPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPeer'
type MockIPeerStore_AddPeer_Call struct {
	*mock.Call
}

// AddPeer is a helper method to define mock.On call
//   - peerId string
func (_e *MockIPeerStore_Expecter) AddPeer(peerId interface{}) *MockIPeerStore_AddPeer_Call {
	return &MockIPeerStore_AddPeer_Call{Call: _e.mock.On("AddPeer", peerId)}
}

func (_c *MockIPeerStore_AddPeer_Call) Run(run func(peerId string)) *MockIPeerStore_AddPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIPeerStore_AddPeer_Call) Return() *MockIPeerStore_AddPeer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPeerStore_AddPeer_Call) RunAndReturn(run func(string)) *MockIPeerStore_AddPeer_Call {
	_c.Run(run)
	return _c
}

// GetPeers provides a mock function with no fields
func (_m *MockIPeerStore) GetPeers() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPeers")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockIPeerStore_GetPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPeers'
type MockIPeerStore_GetPeers_Call struct {
	*mock.Call
}

// GetPeers is a helper method to define mock.On call
func (_e *MockIPeerStore_Expecter) GetPeers() *MockIPeerStore_GetPeers_Call {
	return &MockIPeerStore_GetPeers_Call{Call: _e.mock.On("GetPeers")}
}

func (_c *MockIPeerStore_GetPeers_Call) Run(run func()) *MockIPeerStore_GetPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPeerStore_GetPeers_Call) Return(_a0 []string) *MockIPeerStore_GetPeers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPeerStore_GetPeers_Call) RunAndReturn(run func() []string) *MockIPeerStore_GetPeers_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePeer provides a mock function with given fields: peerId
func (_m *MockIPeerStore) RemovePeer(peerId string) {
	_m.Called(peerId)
}

// MockIPeerStore_RemovePeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePeer'
type MockIPeerStore_RemovePeer_Call struct {
	*mock.Call
}

// RemovePeer is a helper method to define mock.On call
//   - peerId string
func (_e *MockIPeerStore_Expecter) RemovePeer(peerId interface{}) *MockIPeerStore_RemovePeer_Call {
	return &MockIPeerStore_RemovePeer_Call{Call: _e.mock.On("RemovePeer", peerId)}
}

func (_c *MockIPeerStore_RemovePeer_Call) Run(run func(peerId string)) *MockIPeerStore_RemovePeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIPeerStore_RemovePeer_Call) Return() *MockIPeerStore_RemovePeer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPeerStore_RemovePeer_Call) RunAndReturn(run func(string)) *MockIPeerStore_RemovePeer_Call {
	_c.Run(run)
	return _c
}

// SelfID provides a mock function with no fields
func (_m *MockIPeerStore) SelfID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SelfID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIPeerStore_SelfID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelfID'
type MockIPeerStore_SelfID_Call struct {
	*mock.Call
}

// SelfID is a helper method to define mock.On call
func (_e *MockIPeerStore_Expecter) SelfID() *MockIPeerStore_SelfID_Call {
	return &MockIPeerStore_SelfID_Call{Call: _e.mock.On("SelfID")}
}

func (_c *MockIPeerStore_SelfID_Call) Run(run func()) *MockIPeerStore_SelfID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPeerStore_SelfID_Call) Return(_a0 string) *MockIPeerStore_SelfID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPeerStore_SelfID_Call) RunAndReturn(run func() string) *MockIPeerStore_SelfID_Call {
	_c.Call.Return(run)
	return _c
}

// SnapshotOfPeers provides a mock function with no fields
func (_m *MockIPeerStore) SnapshotOfPeers() map[string]time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SnapshotOfPeers")
	}

	var r0 map[string]time.Time
	if rf, ok := ret.Get(0).(func() map[string]time.Time); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]time.Time)
		}
	}

	return r0
}

// MockIPeerStore_SnapshotOfPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SnapshotOfPeers'
type MockIPeerStore_SnapshotOfPeers_Call struct {
	*mock.Call
}

// SnapshotOfPeers is a helper method to define mock.On call
func (_e *MockIPeerStore_Expecter) SnapshotOfPeers() *MockIPeerStore_SnapshotOfPeers_Call {
	return &MockIPeerStore_SnapshotOfPeers_Call{Call: _e.mock.On("SnapshotOfPeers")}
}

func (_c *MockIPeerStore_SnapshotOfPeers_Call) Run(run func()) *MockIPeerStore_SnapshotOfPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPeerStore_SnapshotOfPeers_Call) Return(_a0 map[string]time.Time) *MockIPeerStore_SnapshotOfPeers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPeerStore_SnapshotOfPeers_Call) RunAndReturn(run func() map[string]time.Time) *MockIPeerStore_SnapshotOfPeers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPeerStore creates a new instance of MockIPeerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPeerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPeerStore {
	mock := &MockIPeerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
